<?php
/**
 * CollaboratorApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Legislate API
 *
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CollaboratorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CollaboratorApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteCollaboratorUsingDELETE
     *
     * Delete a Collaborator by its id..
     *
     */
    public function testDeleteCollaboratorUsingDELETE()
    {
    }

    /**
     * Test case for getCollaboratorIdentityFieldsUsingGET
     *
     * Get Identity fields.
     *
     */
    public function testGetCollaboratorIdentityFieldsUsingGET()
    {
    }

    /**
     * Test case for getCollaboratorUsingGET
     *
     * Get contract collaborator details.
     *
     */
    public function testGetCollaboratorUsingGET()
    {
    }

    /**
     * Test case for getCollaboratorsUsingGET
     *
     * Get collaborators for a given contract.
     *
     */
    public function testGetCollaboratorsUsingGET()
    {
    }

    /**
     * Test case for postCollaboratorUsingPOST
     *
     * Create a collaborator given a contract.
     *
     */
    public function testPostCollaboratorUsingPOST()
    {
    }

    /**
     * Test case for postCompanyUsingPOST
     *
     * Create a company given a contract.
     *
     */
    public function testPostCompanyUsingPOST()
    {
    }

    /**
     * Test case for updateCollaboratorBinaryFileSignatureUsingPATCH
     *
     * Upload a signature to a collaborator.
     *
     */
    public function testUpdateCollaboratorBinaryFileSignatureUsingPATCH()
    {
    }

    /**
     * Test case for updateCollaboratorFieldsUsingPATCH
     *
     * Update collaborator fields.
     *
     */
    public function testUpdateCollaboratorFieldsUsingPATCH()
    {
    }

    /**
     * Test case for updateCollaboratorRolesUsingPATCH
     *
     * Update collaborator role.
     *
     */
    public function testUpdateCollaboratorRolesUsingPATCH()
    {
    }

    /**
     * Test case for updateCollaboratorSignatureUsingPATCH
     *
     * Upload a signature to a collaborator.
     *
     */
    public function testUpdateCollaboratorSignatureUsingPATCH()
    {
    }
}
