<?php
/**
 * ContractApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Legislate API
 *
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ContractApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContractApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteContractUsingDELETE
     *
     * Deletes a contract by its id..
     *
     */
    public function testDeleteContractUsingDELETE()
    {
    }

    /**
     * Test case for getContractFileUsingGET
     *
     * Get contract pdf.
     *
     */
    public function testGetContractFileUsingGET()
    {
    }

    /**
     * Test case for getContractHtmlUsingGET
     *
     * Get contract html.
     *
     */
    public function testGetContractHtmlUsingGET()
    {
    }

    /**
     * Test case for getContractUsingGET
     *
     * Get contract details..
     *
     */
    public function testGetContractUsingGET()
    {
    }

    /**
     * Test case for getContractsUsingGET
     *
     * Get contracts in a team.
     *
     */
    public function testGetContractsUsingGET()
    {
    }

    /**
     * Test case for postContractUsingPOST
     *
     * Create a contract with an auto-generated bundle..
     *
     */
    public function testPostContractUsingPOST()
    {
    }

    /**
     * Test case for updateContractUsingPATCH
     *
     * Updates a contract..
     *
     */
    public function testUpdateContractUsingPATCH()
    {
    }
}
