<?php
/**
 * ContractTypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Legislate API
 *
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ContractTypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContractTypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getContractTypePerTeamUsingGET
     *
     * Get information relative a given contract type..
     *
     */
    public function testGetContractTypePerTeamUsingGET()
    {
    }

    /**
     * Test case for getContractTypeUsingGET
     *
     * Get contract type terms..
     *
     */
    public function testGetContractTypeUsingGET()
    {
    }

    /**
     * Test case for getContractTypesPerTeamUsingGET
     *
     * Get contract types of a team.
     *
     */
    public function testGetContractTypesPerTeamUsingGET()
    {
    }

    /**
     * Test case for getContractTypesUsingGET
     *
     * Get public contract types..
     *
     */
    public function testGetContractTypesUsingGET()
    {
    }
}
